#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: false #Set true for H2db
    hibernate:
      ddl-auto: none #Set auto for H2db
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5431/voting
    username: user
    password: password
  # Jackson Serialization Issue Resolver